### ISSUE TITLE
S3 integration example using MinIO

### ISSUE THREAD

**Issue by kaskabayev** [saracen/gobuildcache#1]
Hey, I want to submit the following changes to support the S3 integration as an example out of the box.

Here is the `docker-compose.yaml`

```
services:
  minio:
    image: minio/minio
    ports:
      - "9090:9000"  # API
      - "9091:9001"  # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin &&
      /usr/bin/mc mb myminio/buildcache"

volumes:
  minio_data:
```

# Usage example

## S3 integration

You can use the MinIO S3 compatible storage provider to test this tool.
Spin up MinIO using Docker:
```shell
docker compose up -d
```

Export the following environment variables:
```shell
export GOCACHEPROG="./gocache -p buildcache 's3://buildcache?endpoint=http://localhost:9090&use_path_style=true&region=us-east-1'"
export AWS_ACCESS_KEY_ID=minioadmin
export AWS_SECRET_ACCESS_KEY=minioadmin
```

Open the MinIO console at the MinIO console at http://localhost:9091 and check uploaded files.
